# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def AnswerFromContext(self, question: str,current_utc: str,hints: str,retrieval_json: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ContextAnswer:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AnswerFromContext(question=question,current_utc=current_utc,hints=hints,retrieval_json=retrieval_json,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AnswerFromContext", args={
                "question": question,"current_utc": current_utc,"hints": hints,"retrieval_json": retrieval_json,
            })
            return typing.cast(types.ContextAnswer, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def CompileContextBrief(self, candidate_profile_json: str,candidate_records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ContextBriefDraftOutput:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CompileContextBrief(candidate_profile_json=candidate_profile_json,candidate_records_json=candidate_records_json,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CompileContextBrief", args={
                "candidate_profile_json": candidate_profile_json,"candidate_records_json": candidate_records_json,
            })
            return typing.cast(types.ContextBriefDraftOutput, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def CurateContextCluster(self, run_instruction: str,cluster_id: str,records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ContextCurationPlan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CurateContextCluster(run_instruction=run_instruction,cluster_id=cluster_id,records_json=records_json,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CurateContextCluster", args={
                "run_instruction": run_instruction,"cluster_id": cluster_id,"records_json": records_json,
            })
            return typing.cast(types.ContextCurationPlan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def CurateRecordHealthBatch(self, run_instruction: str,batch_id: str,records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ContextCurationPlan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CurateRecordHealthBatch(run_instruction=run_instruction,batch_id=batch_id,records_json=records_json,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CurateRecordHealthBatch", args={
                "run_instruction": run_instruction,"batch_id": batch_id,"records_json": records_json,
            })
            return typing.cast(types.ContextCurationPlan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def FilterDurableSignal(self, run_instruction: str,episode_summary: str,durable_findings_summary: str,implementation_summary: str,existing_record_manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SignalFilterResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.FilterDurableSignal(run_instruction=run_instruction,episode_summary=episode_summary,durable_findings_summary=durable_findings_summary,implementation_summary=implementation_summary,existing_record_manifest=existing_record_manifest,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="FilterDurableSignal", args={
                "run_instruction": run_instruction,"episode_summary": episode_summary,"durable_findings_summary": durable_findings_summary,"implementation_summary": implementation_summary,"existing_record_manifest": existing_record_manifest,
            })
            return typing.cast(types.SignalFilterResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ObserveSourceWindow(self, run_instruction: str,prior_episode_summary: str,prior_findings_summary: str,source_window: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SourceWindowScan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ObserveSourceWindow(run_instruction=run_instruction,prior_episode_summary=prior_episode_summary,prior_findings_summary=prior_findings_summary,source_window=source_window,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ObserveSourceWindow", args={
                "run_instruction": run_instruction,"prior_episode_summary": prior_episode_summary,"prior_findings_summary": prior_findings_summary,"source_window": source_window,
            })
            return typing.cast(types.SourceWindowScan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def PlanContextRetrieval(self, question: str,current_utc: str,hints: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ContextRetrievalPlan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.PlanContextRetrieval(question=question,current_utc=current_utc,hints=hints,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="PlanContextRetrieval", args={
                "question": question,"current_utc": current_utc,"hints": hints,
            })
            return typing.cast(types.ContextRetrievalPlan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ReviewSynthesizedContextRecords(self, run_instruction: str,durable_findings_summary: str,existing_record_manifest: str,synthesized_records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SynthesizedContextRecords:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ReviewSynthesizedContextRecords(run_instruction=run_instruction,durable_findings_summary=durable_findings_summary,existing_record_manifest=existing_record_manifest,synthesized_records_json=synthesized_records_json,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ReviewSynthesizedContextRecords", args={
                "run_instruction": run_instruction,"durable_findings_summary": durable_findings_summary,"existing_record_manifest": existing_record_manifest,"synthesized_records_json": synthesized_records_json,
            })
            return typing.cast(types.SynthesizedContextRecords, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SynthesizeContextRecords(self, run_instruction: str,episode_summary: str,durable_findings_summary: str,existing_record_manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SynthesizedContextRecords:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SynthesizeContextRecords(run_instruction=run_instruction,episode_summary=episode_summary,durable_findings_summary=durable_findings_summary,existing_record_manifest=existing_record_manifest,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SynthesizeContextRecords", args={
                "run_instruction": run_instruction,"episode_summary": episode_summary,"durable_findings_summary": durable_findings_summary,"existing_record_manifest": existing_record_manifest,
            })
            return typing.cast(types.SynthesizedContextRecords, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerFromContext(self, question: str,current_utc: str,hints: str,retrieval_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ContextAnswer, types.ContextAnswer]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AnswerFromContext", args={
            "question": question,"current_utc": current_utc,"hints": hints,"retrieval_json": retrieval_json,
        })
        return baml_py.BamlStream[stream_types.ContextAnswer, types.ContextAnswer](
          __result__,
          lambda x: typing.cast(stream_types.ContextAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ContextAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CompileContextBrief(self, candidate_profile_json: str,candidate_records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ContextBriefDraftOutput, types.ContextBriefDraftOutput]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CompileContextBrief", args={
            "candidate_profile_json": candidate_profile_json,"candidate_records_json": candidate_records_json,
        })
        return baml_py.BamlStream[stream_types.ContextBriefDraftOutput, types.ContextBriefDraftOutput](
          __result__,
          lambda x: typing.cast(stream_types.ContextBriefDraftOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ContextBriefDraftOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CurateContextCluster(self, run_instruction: str,cluster_id: str,records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ContextCurationPlan, types.ContextCurationPlan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CurateContextCluster", args={
            "run_instruction": run_instruction,"cluster_id": cluster_id,"records_json": records_json,
        })
        return baml_py.BamlStream[stream_types.ContextCurationPlan, types.ContextCurationPlan](
          __result__,
          lambda x: typing.cast(stream_types.ContextCurationPlan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ContextCurationPlan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CurateRecordHealthBatch(self, run_instruction: str,batch_id: str,records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ContextCurationPlan, types.ContextCurationPlan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CurateRecordHealthBatch", args={
            "run_instruction": run_instruction,"batch_id": batch_id,"records_json": records_json,
        })
        return baml_py.BamlStream[stream_types.ContextCurationPlan, types.ContextCurationPlan](
          __result__,
          lambda x: typing.cast(stream_types.ContextCurationPlan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ContextCurationPlan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def FilterDurableSignal(self, run_instruction: str,episode_summary: str,durable_findings_summary: str,implementation_summary: str,existing_record_manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SignalFilterResult, types.SignalFilterResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="FilterDurableSignal", args={
            "run_instruction": run_instruction,"episode_summary": episode_summary,"durable_findings_summary": durable_findings_summary,"implementation_summary": implementation_summary,"existing_record_manifest": existing_record_manifest,
        })
        return baml_py.BamlStream[stream_types.SignalFilterResult, types.SignalFilterResult](
          __result__,
          lambda x: typing.cast(stream_types.SignalFilterResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SignalFilterResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ObserveSourceWindow(self, run_instruction: str,prior_episode_summary: str,prior_findings_summary: str,source_window: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SourceWindowScan, types.SourceWindowScan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ObserveSourceWindow", args={
            "run_instruction": run_instruction,"prior_episode_summary": prior_episode_summary,"prior_findings_summary": prior_findings_summary,"source_window": source_window,
        })
        return baml_py.BamlStream[stream_types.SourceWindowScan, types.SourceWindowScan](
          __result__,
          lambda x: typing.cast(stream_types.SourceWindowScan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SourceWindowScan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def PlanContextRetrieval(self, question: str,current_utc: str,hints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ContextRetrievalPlan, types.ContextRetrievalPlan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="PlanContextRetrieval", args={
            "question": question,"current_utc": current_utc,"hints": hints,
        })
        return baml_py.BamlStream[stream_types.ContextRetrievalPlan, types.ContextRetrievalPlan](
          __result__,
          lambda x: typing.cast(stream_types.ContextRetrievalPlan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ContextRetrievalPlan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ReviewSynthesizedContextRecords(self, run_instruction: str,durable_findings_summary: str,existing_record_manifest: str,synthesized_records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SynthesizedContextRecords, types.SynthesizedContextRecords]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ReviewSynthesizedContextRecords", args={
            "run_instruction": run_instruction,"durable_findings_summary": durable_findings_summary,"existing_record_manifest": existing_record_manifest,"synthesized_records_json": synthesized_records_json,
        })
        return baml_py.BamlStream[stream_types.SynthesizedContextRecords, types.SynthesizedContextRecords](
          __result__,
          lambda x: typing.cast(stream_types.SynthesizedContextRecords, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SynthesizedContextRecords, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SynthesizeContextRecords(self, run_instruction: str,episode_summary: str,durable_findings_summary: str,existing_record_manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SynthesizedContextRecords, types.SynthesizedContextRecords]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SynthesizeContextRecords", args={
            "run_instruction": run_instruction,"episode_summary": episode_summary,"durable_findings_summary": durable_findings_summary,"existing_record_manifest": existing_record_manifest,
        })
        return baml_py.BamlStream[stream_types.SynthesizedContextRecords, types.SynthesizedContextRecords](
          __result__,
          lambda x: typing.cast(stream_types.SynthesizedContextRecords, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SynthesizedContextRecords, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnswerFromContext(self, question: str,current_utc: str,hints: str,retrieval_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnswerFromContext", args={
            "question": question,"current_utc": current_utc,"hints": hints,"retrieval_json": retrieval_json,
        }, mode="request")
        return __result__
    async def CompileContextBrief(self, candidate_profile_json: str,candidate_records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CompileContextBrief", args={
            "candidate_profile_json": candidate_profile_json,"candidate_records_json": candidate_records_json,
        }, mode="request")
        return __result__
    async def CurateContextCluster(self, run_instruction: str,cluster_id: str,records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CurateContextCluster", args={
            "run_instruction": run_instruction,"cluster_id": cluster_id,"records_json": records_json,
        }, mode="request")
        return __result__
    async def CurateRecordHealthBatch(self, run_instruction: str,batch_id: str,records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CurateRecordHealthBatch", args={
            "run_instruction": run_instruction,"batch_id": batch_id,"records_json": records_json,
        }, mode="request")
        return __result__
    async def FilterDurableSignal(self, run_instruction: str,episode_summary: str,durable_findings_summary: str,implementation_summary: str,existing_record_manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FilterDurableSignal", args={
            "run_instruction": run_instruction,"episode_summary": episode_summary,"durable_findings_summary": durable_findings_summary,"implementation_summary": implementation_summary,"existing_record_manifest": existing_record_manifest,
        }, mode="request")
        return __result__
    async def ObserveSourceWindow(self, run_instruction: str,prior_episode_summary: str,prior_findings_summary: str,source_window: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ObserveSourceWindow", args={
            "run_instruction": run_instruction,"prior_episode_summary": prior_episode_summary,"prior_findings_summary": prior_findings_summary,"source_window": source_window,
        }, mode="request")
        return __result__
    async def PlanContextRetrieval(self, question: str,current_utc: str,hints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PlanContextRetrieval", args={
            "question": question,"current_utc": current_utc,"hints": hints,
        }, mode="request")
        return __result__
    async def ReviewSynthesizedContextRecords(self, run_instruction: str,durable_findings_summary: str,existing_record_manifest: str,synthesized_records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ReviewSynthesizedContextRecords", args={
            "run_instruction": run_instruction,"durable_findings_summary": durable_findings_summary,"existing_record_manifest": existing_record_manifest,"synthesized_records_json": synthesized_records_json,
        }, mode="request")
        return __result__
    async def SynthesizeContextRecords(self, run_instruction: str,episode_summary: str,durable_findings_summary: str,existing_record_manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SynthesizeContextRecords", args={
            "run_instruction": run_instruction,"episode_summary": episode_summary,"durable_findings_summary": durable_findings_summary,"existing_record_manifest": existing_record_manifest,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnswerFromContext(self, question: str,current_utc: str,hints: str,retrieval_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnswerFromContext", args={
            "question": question,"current_utc": current_utc,"hints": hints,"retrieval_json": retrieval_json,
        }, mode="stream")
        return __result__
    async def CompileContextBrief(self, candidate_profile_json: str,candidate_records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CompileContextBrief", args={
            "candidate_profile_json": candidate_profile_json,"candidate_records_json": candidate_records_json,
        }, mode="stream")
        return __result__
    async def CurateContextCluster(self, run_instruction: str,cluster_id: str,records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CurateContextCluster", args={
            "run_instruction": run_instruction,"cluster_id": cluster_id,"records_json": records_json,
        }, mode="stream")
        return __result__
    async def CurateRecordHealthBatch(self, run_instruction: str,batch_id: str,records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CurateRecordHealthBatch", args={
            "run_instruction": run_instruction,"batch_id": batch_id,"records_json": records_json,
        }, mode="stream")
        return __result__
    async def FilterDurableSignal(self, run_instruction: str,episode_summary: str,durable_findings_summary: str,implementation_summary: str,existing_record_manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FilterDurableSignal", args={
            "run_instruction": run_instruction,"episode_summary": episode_summary,"durable_findings_summary": durable_findings_summary,"implementation_summary": implementation_summary,"existing_record_manifest": existing_record_manifest,
        }, mode="stream")
        return __result__
    async def ObserveSourceWindow(self, run_instruction: str,prior_episode_summary: str,prior_findings_summary: str,source_window: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ObserveSourceWindow", args={
            "run_instruction": run_instruction,"prior_episode_summary": prior_episode_summary,"prior_findings_summary": prior_findings_summary,"source_window": source_window,
        }, mode="stream")
        return __result__
    async def PlanContextRetrieval(self, question: str,current_utc: str,hints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PlanContextRetrieval", args={
            "question": question,"current_utc": current_utc,"hints": hints,
        }, mode="stream")
        return __result__
    async def ReviewSynthesizedContextRecords(self, run_instruction: str,durable_findings_summary: str,existing_record_manifest: str,synthesized_records_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ReviewSynthesizedContextRecords", args={
            "run_instruction": run_instruction,"durable_findings_summary": durable_findings_summary,"existing_record_manifest": existing_record_manifest,"synthesized_records_json": synthesized_records_json,
        }, mode="stream")
        return __result__
    async def SynthesizeContextRecords(self, run_instruction: str,episode_summary: str,durable_findings_summary: str,existing_record_manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SynthesizeContextRecords", args={
            "run_instruction": run_instruction,"episode_summary": episode_summary,"durable_findings_summary": durable_findings_summary,"existing_record_manifest": existing_record_manifest,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))