# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerFromContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnswerFromContext", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextAnswer, __result__)

    def CompileContextBrief(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextBriefDraftOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CompileContextBrief", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextBriefDraftOutput, __result__)

    def CurateContextCluster(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextCurationPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CurateContextCluster", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextCurationPlan, __result__)

    def CurateRecordHealthBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextCurationPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CurateRecordHealthBatch", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextCurationPlan, __result__)

    def ExtractCodingProjectIdentitySlot(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodingProjectIdentitySlotRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCodingProjectIdentitySlot", llm_response=llm_response, mode="request")
        return typing.cast(types.CodingProjectIdentitySlotRecords, __result__)

    def ExtractCodingStrategySlots(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodingStrategySlotRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCodingStrategySlots", llm_response=llm_response, mode="request")
        return typing.cast(types.CodingStrategySlotRecords, __result__)

    def FilterDurableSignal(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SignalFilterResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FilterDurableSignal", llm_response=llm_response, mode="request")
        return typing.cast(types.SignalFilterResult, __result__)

    def GuardSynthesizedContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GuardSynthesizedContextRecords", llm_response=llm_response, mode="request")
        return typing.cast(types.SynthesizedContextRecords, __result__)

    def LinkContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextGraphPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="LinkContextRecords", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextGraphPlan, __result__)

    def ObserveSourceWindow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SourceWindowScan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ObserveSourceWindow", llm_response=llm_response, mode="request")
        return typing.cast(types.SourceWindowScan, __result__)

    def PlanContextRetrieval(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextRetrievalPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanContextRetrieval", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextRetrievalPlan, __result__)

    def PolishCodingEvalContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodingEvalPolishedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PolishCodingEvalContextRecords", llm_response=llm_response, mode="request")
        return typing.cast(types.CodingEvalPolishedContextRecords, __result__)

    def PolishContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PolishContextRecords", llm_response=llm_response, mode="request")
        return typing.cast(types.SynthesizedContextRecords, __result__)

    def ReviewContextGraphLinks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextGraphPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ReviewContextGraphLinks", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextGraphPlan, __result__)

    def SelectCodingDurableRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodingRecordRetentionResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectCodingDurableRecords", llm_response=llm_response, mode="request")
        return typing.cast(types.CodingRecordRetentionResult, __result__)

    def SynthesizeContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeContextRecords", llm_response=llm_response, mode="request")
        return typing.cast(types.SynthesizedContextRecords, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerFromContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnswerFromContext", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextAnswer, __result__)

    def CompileContextBrief(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextBriefDraftOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CompileContextBrief", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextBriefDraftOutput, __result__)

    def CurateContextCluster(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextCurationPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CurateContextCluster", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextCurationPlan, __result__)

    def CurateRecordHealthBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextCurationPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CurateRecordHealthBatch", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextCurationPlan, __result__)

    def ExtractCodingProjectIdentitySlot(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodingProjectIdentitySlotRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCodingProjectIdentitySlot", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodingProjectIdentitySlotRecords, __result__)

    def ExtractCodingStrategySlots(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodingStrategySlotRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCodingStrategySlots", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodingStrategySlotRecords, __result__)

    def FilterDurableSignal(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SignalFilterResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FilterDurableSignal", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SignalFilterResult, __result__)

    def GuardSynthesizedContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GuardSynthesizedContextRecords", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SynthesizedContextRecords, __result__)

    def LinkContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextGraphPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="LinkContextRecords", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextGraphPlan, __result__)

    def ObserveSourceWindow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SourceWindowScan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ObserveSourceWindow", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SourceWindowScan, __result__)

    def PlanContextRetrieval(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextRetrievalPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanContextRetrieval", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextRetrievalPlan, __result__)

    def PolishCodingEvalContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodingEvalPolishedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PolishCodingEvalContextRecords", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodingEvalPolishedContextRecords, __result__)

    def PolishContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PolishContextRecords", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SynthesizedContextRecords, __result__)

    def ReviewContextGraphLinks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextGraphPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ReviewContextGraphLinks", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextGraphPlan, __result__)

    def SelectCodingDurableRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodingRecordRetentionResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectCodingDurableRecords", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodingRecordRetentionResult, __result__)

    def SynthesizeContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeContextRecords", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SynthesizedContextRecords, __result__)

    