# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerFromContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnswerFromContext", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextAnswer, __result__)

    def CompileContextBrief(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextBriefDraftOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CompileContextBrief", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextBriefDraftOutput, __result__)

    def CurateContextCluster(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextCurationPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CurateContextCluster", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextCurationPlan, __result__)

    def CurateRecordHealthBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextCurationPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CurateRecordHealthBatch", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextCurationPlan, __result__)

    def FilterDurableSignal(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SignalFilterResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FilterDurableSignal", llm_response=llm_response, mode="request")
        return typing.cast(types.SignalFilterResult, __result__)

    def ObserveSourceWindow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SourceWindowScan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ObserveSourceWindow", llm_response=llm_response, mode="request")
        return typing.cast(types.SourceWindowScan, __result__)

    def PlanContextRetrieval(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContextRetrievalPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanContextRetrieval", llm_response=llm_response, mode="request")
        return typing.cast(types.ContextRetrievalPlan, __result__)

    def ReviewSynthesizedContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ReviewSynthesizedContextRecords", llm_response=llm_response, mode="request")
        return typing.cast(types.SynthesizedContextRecords, __result__)

    def SynthesizeContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeContextRecords", llm_response=llm_response, mode="request")
        return typing.cast(types.SynthesizedContextRecords, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerFromContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnswerFromContext", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextAnswer, __result__)

    def CompileContextBrief(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextBriefDraftOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CompileContextBrief", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextBriefDraftOutput, __result__)

    def CurateContextCluster(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextCurationPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CurateContextCluster", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextCurationPlan, __result__)

    def CurateRecordHealthBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextCurationPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CurateRecordHealthBatch", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextCurationPlan, __result__)

    def FilterDurableSignal(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SignalFilterResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FilterDurableSignal", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SignalFilterResult, __result__)

    def ObserveSourceWindow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SourceWindowScan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ObserveSourceWindow", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SourceWindowScan, __result__)

    def PlanContextRetrieval(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContextRetrievalPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanContextRetrieval", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContextRetrievalPlan, __result__)

    def ReviewSynthesizedContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ReviewSynthesizedContextRecords", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SynthesizedContextRecords, __result__)

    def SynthesizeContextRecords(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SynthesizedContextRecords:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeContextRecords", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SynthesizedContextRecords, __result__)

    