# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (17)
# #########################################################################

class ContextAnswer(BaseModel):
    answer: typing.Optional[str] = None
    supporting_record_ids: typing.List[str]

class ContextBriefDraftOutput(BaseModel):
    summary: typing.List["ContextBriefLineDraft"]
    start_here: typing.List["ContextBriefLineDraft"]
    current_handoff: typing.List["ContextBriefLineDraft"]
    decisions: typing.List["ContextBriefLineDraft"] = Field(description='Only cite candidate records whose kind is decision.')
    constraints_preferences: typing.List["ContextBriefLineDraft"] = Field(description='Only cite candidate records whose kind is preference or constraint.')
    project_facts: typing.List["ContextBriefLineDraft"] = Field(description='Only cite candidate records whose kind is fact.')
    open_risks: typing.List["ContextBriefLineDraft"]
    follow_up_queries: typing.List["ContextBriefLineDraft"]

class ContextBriefLineDraft(BaseModel):
    text: typing.Optional[str] = Field(default=None, description='Compact memory statement without inline citations.')
    record_ids: typing.List[str] = Field(description='Exact source record IDs copied from the candidate records.')

class ContextCurationAction(BaseModel):
    action_type: typing.Optional[types.ContextCuratorActionType] = None
    record_id: typing.Optional[str] = None
    replacement_record_id: typing.Optional[str] = None
    reason: typing.Optional[str] = None
    patch: typing.Optional["ContextCuratorRecordPatch"] = None

class ContextCurationPlan(BaseModel):
    actions: typing.List["ContextCurationAction"]
    completion_summary: typing.Optional[str] = None

class ContextCuratorRecordPatch(BaseModel):
    kind: typing.Optional[types.ContextCuratorRecordKind] = None
    title: typing.Optional[str] = None
    body: typing.Optional[str] = None
    status: typing.Optional[types.RecordStatus] = None
    valid_from: typing.Optional[str] = None
    valid_until: typing.Optional[str] = None
    decision: typing.Optional[str] = None
    why: typing.Optional[str] = None
    alternatives: typing.Optional[str] = None
    consequences: typing.Optional[str] = None
    user_intent: typing.Optional[str] = None
    what_happened: typing.Optional[str] = None
    outcomes: typing.Optional[str] = None

class ContextGraphLink(BaseModel):
    source_record_id: typing.Optional[str] = None
    target_record_id: typing.Optional[str] = None
    relation_kind: typing.Optional[types.ContextGraphRelationKind] = None
    label: typing.Optional[str] = None
    rationale: typing.Optional[str] = None
    evidence_record_ids: typing.List[str]
    confidence: typing.Optional[float] = None

class ContextGraphPlan(BaseModel):
    links: typing.List["ContextGraphLink"]
    completion_summary: typing.Optional[str] = None

class ContextRetrievalAction(BaseModel):
    action_type: typing.Optional[types.ContextRetrievalActionType] = None
    query: typing.Optional[str] = None
    kind: typing.Optional[types.ContextRecordKind] = None
    status: typing.Optional[str] = None
    source_session_id: typing.Optional[str] = None
    created_since: typing.Optional[str] = None
    created_until: typing.Optional[str] = None
    updated_since: typing.Optional[str] = None
    updated_until: typing.Optional[str] = None
    valid_at: typing.Optional[str] = None
    include_archived: typing.Optional[bool] = None
    order_by: typing.Optional[str] = None
    limit: typing.Optional[int] = None
    rationale: typing.Optional[str] = None

class ContextRetrievalPlan(BaseModel):
    actions: typing.List["ContextRetrievalAction"]
    rationale: typing.Optional[str] = None

class DurableFinding(BaseModel):
    theme: typing.Optional[str] = Field(default=None, description='Short stable theme for this candidate.')
    kind: typing.Optional[types.RecordKind] = Field(default=None, description='Generic durable record kind. Use only decision, preference, constraint, or fact.')
    line: typing.Optional[int] = Field(default=None, description='1-based supporting line when the window gives one.')
    quote: typing.Optional[str] = Field(default=None, description='Short supporting quote from the current window.')
    note: typing.Optional[str] = Field(default=None, description='Compact semantic candidate. Avoid action logs and copied errors.')

class DurableRecordDraft(BaseModel):
    kind: typing.Optional[types.RecordKind] = Field(default=None, description='Generic durable record kind.')
    title: typing.Optional[str] = Field(default=None, description='Short standalone durable title.')
    body: typing.Optional[str] = Field(default=None, description='Compact standalone durable body.')
    status: typing.Optional[types.RecordStatus] = Field(default=None, description='Use active for every reusable durable record.')
    decision: typing.Optional[str] = Field(default=None, description='Decision text only when kind is decision and the source supports both the choice and why.')
    why: typing.Optional[str] = Field(default=None, description='Decision rationale only when the source directly supports it.')
    alternatives: typing.Optional[str] = Field(default=None, description='Decision alternatives only when explicitly supported by the source.')
    consequences: typing.Optional[str] = Field(default=None, description='Decision consequences only when explicitly supported by the source.')
    source_event_refs: typing.List[str] = Field(description='Trace line refs that directly support this durable record, for example line:12. Use [] only when no source line is available.')
    evidence_refs: typing.List[str] = Field(description='Short evidence refs or quotes that directly support this durable record.')

class EpisodeDraft(BaseModel):
    title: typing.Optional[str] = Field(default=None, description='Short source-session title. Describe the original activity, not Lerim ingestion work.')
    body: typing.Optional[str] = Field(default=None, description='Compact episode body about the original source session. Do not describe created records or ingestion work.')
    status: typing.Optional[types.RecordStatus] = Field(default=None, description='Use archived for routine/no-durable sessions; active only when the episode itself remains useful.')
    user_intent: typing.Optional[str] = Field(default=None, description='What the user wanted in this source session, in source-domain terms.')
    what_happened: typing.Optional[str] = Field(default=None, description='What the source session actually did, in source-domain terms.')
    outcomes: typing.Optional[str] = Field(default=None, description='Optional concise outcome.')
    source_event_refs: typing.List[str] = Field(description='Trace line refs that support this episode, for example line:12. Use [] only when no source line exists.')
    evidence_refs: typing.List[str] = Field(description='Short evidence refs or quotes that support this episode. Use [] when no evidence ref is available.')

class ImplementationFinding(BaseModel):
    theme: typing.Optional[str] = Field(default=None, description='Short theme for source-session-local evidence or noise.')
    line: typing.Optional[int] = Field(default=None, description='1-based supporting line when the window gives one.')
    quote: typing.Optional[str] = Field(default=None, description='Short supporting quote from the current window.')
    note: typing.Optional[str] = Field(default=None, description='Compact note explaining why this is only execution evidence, a discarded hypothesis, or local support.')

class SignalFilterResult(BaseModel):
    kept_durable_findings: typing.List["DurableFinding"] = Field(description='Durable findings that passed the final reuse and dedupe filter.')
    rejected_findings: typing.List["DurableFinding"] = Field(description='Candidate durable findings rejected as weak, duplicate, source-local, or implementation-only.')
    filtering_summary: typing.Optional[str] = Field(default=None, description='Compact explanation of the filtering decision.')

class SourceWindowScan(BaseModel):
    episode_update: typing.Optional[str] = Field(default=None, description='Compact update for the final episode summary. May be omitted when this window adds nothing.')
    durable_findings: typing.List["DurableFinding"] = Field(description='Reusable decisions, preferences, constraints, and facts found in this window.')
    implementation_findings: typing.List["ImplementationFinding"] = Field(description='Implementation evidence, discarded hypotheses, and local details useful only as support/noise.')
    discarded_noise: typing.List[str] = Field(description='Short descriptions of noisy categories intentionally not saved.')

class SynthesizedContextRecords(BaseModel):
    episode: typing.Optional["EpisodeDraft"] = Field(default=None, description='Exactly one current-session episode record draft.')
    durable_records: typing.List["DurableRecordDraft"] = Field(description='Zero or more durable records.')
    completion_summary: typing.Optional[str] = Field(default=None, description='Brief summary of ingestion work for final_result/reporting.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
