# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (7)
# #########################################################################

class ContextCuratorActionType(str, Enum):
    NOOP = "NOOP"
    REVISE = "REVISE"
    ARCHIVE = "ARCHIVE"
    SUPERSEDE = "SUPERSEDE"

class ContextCuratorRecordKind(str, Enum):
    DECISION = "DECISION"
    PREFERENCE = "PREFERENCE"
    CONSTRAINT = "CONSTRAINT"
    FACT = "FACT"
    EPISODE = "EPISODE"

class ContextGraphRelationKind(str, Enum):
    SUPPORTS = "SUPPORTS"
    REFINES = "REFINES"
    DEPENDS_ON = "DEPENDS_ON"
    CONTRADICTS = "CONTRADICTS"
    SAME_TOPIC = "SAME_TOPIC"
    EVIDENCE_FOR = "EVIDENCE_FOR"
    SUPERSEDES = "SUPERSEDES"
    RELATED = "RELATED"

class ContextRecordKind(str, Enum):
    DECISION = "DECISION"
    PREFERENCE = "PREFERENCE"
    CONSTRAINT = "CONSTRAINT"
    FACT = "FACT"
    EPISODE = "EPISODE"

class ContextRetrievalActionType(str, Enum):
    COUNT = "COUNT"
    LIST = "LIST"
    SEARCH = "SEARCH"

class RecordKind(str, Enum):
    DECISION = "DECISION"
    PREFERENCE = "PREFERENCE"
    CONSTRAINT = "CONSTRAINT"
    FACT = "FACT"

class RecordStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"

# #########################################################################
# Generated classes (23)
# #########################################################################

class CodingEvalPolishedContextRecords(BaseModel):
    episode: "EpisodeDraft" = Field(description='Exactly one current-session episode record draft.')
    silent_change_feedback_record: typing.Optional["DurableRecordDraft"] = Field(default=None, description='User feedback correcting a silent model/provider/scope/architecture/cost-tier substitution. Null when absent.')
    model_size_priority_record: typing.Optional["DurableRecordDraft"] = Field(default=None, description='User priority for small/local/hardware-friendly model size or locality. Null when absent.')
    provider_cost_record: typing.Optional["DurableRecordDraft"] = Field(default=None, description='User provider/cost/subscription preference, including teacher/provider choice. Null when absent.')
    user_strategy_records: typing.List["DurableRecordDraft"] = Field(description='Visible user feedback, user preferences, cost/locality/provider constraints, teacher-model preferences, and model-size priorities. Use [] when absent.')
    role_split_record: typing.Optional["DurableRecordDraft"] = Field(default=None, description='Semantic project decision assigning local models and cloud providers to different roles. Null when absent.')
    upstream_bug_report_record: typing.Optional["DurableRecordDraft"] = Field(default=None, description='Externally reported upstream bug or issue/PR fact, without local workaround mechanics. Null when absent.')
    project_identity_fact: typing.Optional["FixedKindRecordDraft"] = Field(default=None, description='Configured external service/project identity as a fact, including project name or dashboard/workspace URL when source-stated and reusable. Null when absent.')
    model_setting_fact: typing.Optional["FixedKindRecordDraft"] = Field(default=None, description='Validated model/runtime setting as a fact. Null when absent.')
    adapter_decision: typing.Optional["FixedKindRecordDraft"] = Field(default=None, description='Adopted adapter approach as a decision. Null when absent.')
    prompt_structure_decision: typing.Optional["FixedKindRecordDraft"] = Field(default=None, description='Adopted prompt-structure approach as a decision. Null when absent.')
    fixture_constraint: typing.Optional["FixedKindRecordDraft"] = Field(default=None, description='Fixture validity or failure-interpretation rule as a constraint. Null when absent.')
    deferred_design_fact: typing.Optional["FixedKindRecordDraft"] = Field(default=None, description='Explicitly deferred concrete design as a fact. Null when absent.')
    other_records: typing.List["DurableRecordDraft"] = Field(description='Other durable coding records that do not fit the eval/debug slots, especially stable user feedback, user preferences, product strategy, architecture decisions, cost/locality constraints, and cloud/local role decisions.')
    completion_summary: typing.Optional[str] = Field(default=None, description='Brief summary of ingestion work for final_result/reporting.')

class CodingProjectIdentitySlotRecords(BaseModel):
    project_identity_fact: typing.Optional["FixedKindRecordDraft"] = Field(default=None, description='Configured external service/project identity as a fact, including project/service name or dashboard/workspace/project URL when source-stated. Null when absent.')

class CodingRecordRetentionDecision(BaseModel):
    record_index: int = Field(description='Zero-based index of the candidate durable record in final_records_json.durable_records.')
    keep: bool = Field(description='True only when the record is durable future context rather than current-task implementation debris.')
    reason: str = Field(description='Short reason for keeping or dropping this record.')

class CodingRecordRetentionResult(BaseModel):
    save_any: bool = Field(description='False when the coding session should be archived with no durable records at all.')
    session_reason: str = Field(description='Short session-level reason for saving or dropping all durable records.')
    decisions: typing.List["CodingRecordRetentionDecision"] = Field(description='One keep/drop decision per candidate durable record.')

class CodingStrategySlotRecords(BaseModel):
    silent_change_feedback_record: typing.Optional["DurableRecordDraft"] = Field(default=None, description='Visible user correction for an unapproved model/provider/scope/architecture/cost-tier change. Null when absent.')
    model_size_priority_record: typing.Optional["DurableRecordDraft"] = Field(default=None, description='Visible user priority for small/local/hardware-friendly model size or locality. Null when absent.')
    provider_cost_record: typing.Optional["DurableRecordDraft"] = Field(default=None, description='Visible user provider/cost/subscription preference, including teacher/provider choice. Null when absent.')
    role_split_record: typing.Optional["DurableRecordDraft"] = Field(default=None, description='Semantic project role split between local models and cloud providers, using source findings as evidence. Null when absent.')

class ContextAnswer(BaseModel):
    answer: str
    supporting_record_ids: typing.List[str]

class ContextBriefDraftOutput(BaseModel):
    summary: typing.List["ContextBriefLineDraft"]
    start_here: typing.List["ContextBriefLineDraft"]
    current_handoff: typing.List["ContextBriefLineDraft"]
    decisions: typing.List["ContextBriefLineDraft"] = Field(description='Only cite candidate records whose kind is decision.')
    constraints_preferences: typing.List["ContextBriefLineDraft"] = Field(description='Only cite candidate records whose kind is preference or constraint.')
    project_facts: typing.List["ContextBriefLineDraft"] = Field(description='Only cite candidate records whose kind is fact.')
    open_risks: typing.List["ContextBriefLineDraft"]
    follow_up_queries: typing.List["ContextBriefLineDraft"]

class ContextBriefLineDraft(BaseModel):
    text: str = Field(description='Compact memory statement without inline citations.')
    record_ids: typing.List[str] = Field(description='Exact source record IDs copied from the candidate records.')

class ContextCurationAction(BaseModel):
    action_type: ContextCuratorActionType
    record_id: str
    replacement_record_id: typing.Optional[str] = None
    reason: str
    patch: typing.Optional["ContextCuratorRecordPatch"] = None

class ContextCurationPlan(BaseModel):
    actions: typing.List["ContextCurationAction"]
    completion_summary: typing.Optional[str] = None

class ContextCuratorRecordPatch(BaseModel):
    kind: ContextCuratorRecordKind
    title: str
    body: str
    status: typing.Optional[RecordStatus] = None
    valid_from: typing.Optional[str] = None
    valid_until: typing.Optional[str] = None
    decision: typing.Optional[str] = None
    why: typing.Optional[str] = None
    alternatives: typing.Optional[str] = None
    consequences: typing.Optional[str] = None
    user_intent: typing.Optional[str] = None
    what_happened: typing.Optional[str] = None
    outcomes: typing.Optional[str] = None

class ContextGraphLink(BaseModel):
    source_record_id: str
    target_record_id: str
    relation_kind: ContextGraphRelationKind
    label: str
    rationale: str
    evidence_record_ids: typing.List[str]
    confidence: float

class ContextGraphPlan(BaseModel):
    links: typing.List["ContextGraphLink"]
    completion_summary: typing.Optional[str] = None

class ContextRetrievalAction(BaseModel):
    action_type: ContextRetrievalActionType
    query: typing.Optional[str] = None
    kind: typing.Optional[ContextRecordKind] = None
    status: typing.Optional[str] = None
    source_session_id: typing.Optional[str] = None
    created_since: typing.Optional[str] = None
    created_until: typing.Optional[str] = None
    updated_since: typing.Optional[str] = None
    updated_until: typing.Optional[str] = None
    valid_at: typing.Optional[str] = None
    include_archived: typing.Optional[bool] = None
    order_by: typing.Optional[str] = None
    limit: typing.Optional[int] = None
    rationale: typing.Optional[str] = None

class ContextRetrievalPlan(BaseModel):
    actions: typing.List["ContextRetrievalAction"]
    rationale: typing.Optional[str] = None

class DurableFinding(BaseModel):
    theme: str = Field(description='Short stable theme for this candidate.')
    kind: RecordKind = Field(description='Generic durable record kind. Use only decision, preference, constraint, or fact.')
    line: typing.Optional[int] = Field(default=None, description='1-based supporting line when the window gives one.')
    quote: typing.Optional[str] = Field(default=None, description='Short supporting quote from the current window.')
    note: str = Field(description='Compact semantic candidate. Avoid action logs and copied errors.')

class DurableRecordDraft(BaseModel):
    kind: RecordKind = Field(description='Generic durable record kind.')
    title: str = Field(description='Short standalone durable title.')
    body: str = Field(description='Compact standalone durable body.')
    status: typing.Optional[RecordStatus] = Field(default=None, description='Use active for every reusable durable record.')
    decision: typing.Optional[str] = Field(default=None, description='Decision text only when kind is decision and the source supports both the choice and why.')
    why: typing.Optional[str] = Field(default=None, description='Decision rationale only when the source directly supports it.')
    alternatives: typing.Optional[str] = Field(default=None, description='Decision alternatives only when explicitly supported by the source.')
    consequences: typing.Optional[str] = Field(default=None, description='Decision consequences only when explicitly supported by the source.')
    source_event_refs: typing.List[str] = Field(description='Trace line refs that directly support this durable record, for example line:12. Use [] only when no source line is available.')
    evidence_refs: typing.List[str] = Field(description='Short evidence refs or quotes that directly support this durable record.')

class EpisodeDraft(BaseModel):
    title: str = Field(description='Short source-session title. Describe the original activity, not Lerim ingestion work.')
    body: str = Field(description='Compact episode body about the original source session. Do not describe created records or ingestion work.')
    status: RecordStatus = Field(description='Use archived for routine/no-durable sessions; active only when the episode itself remains useful.')
    user_intent: str = Field(description='What the user wanted in this source session, in source-domain terms.')
    what_happened: str = Field(description='What the source session actually did, in source-domain terms.')
    outcomes: typing.Optional[str] = Field(default=None, description='Optional concise outcome.')
    source_event_refs: typing.List[str] = Field(description='Trace line refs that support this episode, for example line:12. Use [] only when no source line exists.')
    evidence_refs: typing.List[str] = Field(description='Short evidence refs or quotes that support this episode. Use [] when no evidence ref is available.')

class FixedKindRecordDraft(BaseModel):
    title: str = Field(description='Short standalone durable title.')
    body: str = Field(description='Compact standalone durable body.')
    status: typing.Optional[RecordStatus] = Field(default=None, description='Use active for every reusable durable record.')
    decision: typing.Optional[str] = Field(default=None, description='Decision text only for fixed decision slots.')
    why: typing.Optional[str] = Field(default=None, description='Decision rationale only when source directly supports it.')
    alternatives: typing.Optional[str] = Field(default=None, description='Decision alternatives only when explicitly supported by the source.')
    consequences: typing.Optional[str] = Field(default=None, description='Decision consequences only when explicitly supported by the source.')
    source_event_refs: typing.List[str] = Field(description='Trace line refs that directly support this durable record, for example line:12. Use [] only when no source line is available.')
    evidence_refs: typing.List[str] = Field(description='Short evidence refs or quotes that directly support this durable record.')

class ImplementationFinding(BaseModel):
    theme: str = Field(description='Short theme for source-session-local evidence or noise.')
    line: typing.Optional[int] = Field(default=None, description='1-based supporting line when the window gives one.')
    quote: typing.Optional[str] = Field(default=None, description='Short supporting quote from the current window.')
    note: str = Field(description='Compact note explaining why this is only execution evidence, a discarded hypothesis, or local support.')

class SignalFilterResult(BaseModel):
    kept_durable_findings: typing.List["DurableFinding"] = Field(description='Durable findings that passed the final reuse and dedupe filter.')
    rejected_findings: typing.List["DurableFinding"] = Field(description='Candidate durable findings rejected as weak, duplicate, source-local, or implementation-only.')
    filtering_summary: typing.Optional[str] = Field(default=None, description='Compact explanation of the filtering decision.')

class SourceWindowScan(BaseModel):
    episode_update: typing.Optional[str] = Field(default=None, description='Compact update for the final episode summary. May be omitted when this window adds nothing.')
    durable_findings: typing.List["DurableFinding"] = Field(description='Reusable decisions, preferences, constraints, and facts found in this window.')
    implementation_findings: typing.List["ImplementationFinding"] = Field(description='Implementation evidence, discarded hypotheses, and local details useful only as support/noise.')
    discarded_noise: typing.List[str] = Field(description='Short descriptions of noisy categories intentionally not saved.')

class SynthesizedContextRecords(BaseModel):
    episode: "EpisodeDraft" = Field(description='Exactly one current-session episode record draft.')
    durable_records: typing.List["DurableRecordDraft"] = Field(description='Zero or more durable records.')
    completion_summary: typing.Optional[str] = Field(default=None, description='Brief summary of ingestion work for final_result/reporting.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
