# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DurableRecordDraft": types.DurableRecordDraft,
    "stream_types.DurableRecordDraft": stream_types.DurableRecordDraft,

    "types.EpisodeDraft": types.EpisodeDraft,
    "stream_types.EpisodeDraft": stream_types.EpisodeDraft,

    "types.SynthesizedExtraction": types.SynthesizedExtraction,
    "stream_types.SynthesizedExtraction": stream_types.SynthesizedExtraction,

    "types.TraceWindowFinding": types.TraceWindowFinding,
    "stream_types.TraceWindowFinding": stream_types.TraceWindowFinding,

    "types.TraceWindowScan": types.TraceWindowScan,
    "stream_types.TraceWindowScan": stream_types.TraceWindowScan,


    "types.FindingLevel": types.FindingLevel,

    "types.RecordKind": types.RecordKind,

    "types.RecordStatus": types.RecordStatus,

}