# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class FindingLevel(str, Enum):
    DECISION = "DECISION"
    PREFERENCE = "PREFERENCE"
    FEEDBACK = "FEEDBACK"
    REFERENCE = "REFERENCE"
    CONSTRAINT = "CONSTRAINT"
    FACT = "FACT"
    IMPLEMENTATION = "IMPLEMENTATION"

class RecordKind(str, Enum):
    DECISION = "DECISION"
    PREFERENCE = "PREFERENCE"
    CONSTRAINT = "CONSTRAINT"
    FACT = "FACT"
    REFERENCE = "REFERENCE"

class RecordStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"

# #########################################################################
# Generated classes (5)
# #########################################################################

class DurableRecordDraft(BaseModel):
    kind: RecordKind = Field(description='Durable record kind.')
    title: str = Field(description='Short standalone durable title.')
    body: str = Field(description='Compact standalone durable body.')
    status: typing.Optional[RecordStatus] = Field(default=None, description='Usually active for reusable durable records.')
    valid_from: typing.Optional[str] = None
    valid_until: typing.Optional[str] = None
    decision: typing.Optional[str] = None
    why: typing.Optional[str] = None
    alternatives: typing.Optional[str] = None
    consequences: typing.Optional[str] = None

class EpisodeDraft(BaseModel):
    title: typing.Optional[str] = Field(default=None, description='Optional short title for the current-session episode. Runtime derives one if omitted.')
    body: typing.Optional[str] = Field(default=None, description='Compact episode body. If omitted, runtime builds it from user_intent and what_happened.')
    status: typing.Optional[RecordStatus] = Field(default=None, description='Use archived for routine/no-durable sessions; active only when the episode itself remains useful.')
    user_intent: typing.Optional[str] = Field(default=None, description='What the user wanted in this source session. Runtime fills a generic fallback if omitted.')
    what_happened: typing.Optional[str] = Field(default=None, description='What the session actually did. Runtime fills a generic fallback if omitted.')
    outcomes: typing.Optional[str] = Field(default=None, description='Optional concise outcome.')

class SynthesizedExtraction(BaseModel):
    episode: "EpisodeDraft" = Field(description='Exactly one current-session episode record draft.')
    durable_records: typing.List["DurableRecordDraft"] = Field(description='Zero or more durable records.')
    completion_summary: typing.Optional[str] = Field(default=None, description='Brief summary of extraction work for final_result/reporting.')

class TraceWindowFinding(BaseModel):
    theme: str = Field(description='Short stable theme for this finding.')
    level: FindingLevel = Field(description='Use durable levels for reusable context, implementation for local/noisy evidence.')
    line: typing.Optional[int] = Field(default=None, description='1-based supporting line when the window gives one.')
    quote: typing.Optional[str] = Field(default=None, description='Short supporting quote from the current window.')
    note: str = Field(description='Compact semantic finding. Avoid command logs and copied errors.')

class TraceWindowScan(BaseModel):
    episode_update: typing.Optional[str] = Field(default=None, description='Compact update for the final episode summary. May be omitted when this window adds nothing.')
    durable_findings: typing.List["TraceWindowFinding"] = Field(description='Reusable decisions, preferences, constraints, facts, and references found in this window.')
    implementation_findings: typing.List["TraceWindowFinding"] = Field(description='Implementation evidence, discarded hypotheses, and local details useful only as support/noise.')
    discarded_noise: typing.List[str] = Field(description='Short descriptions of noisy categories intentionally not saved.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
