# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (9)
# #########################################################################

class ExtractAgentStep(BaseModel):
    action: typing.Optional[types.ExtractAction] = None
    rationale: typing.Optional[str] = Field(default=None, description='One short sentence explaining why this is the next action. Do not include hidden chain-of-thought.')
    read_trace: typing.Optional["ReadTraceArgs"] = None
    search_context: typing.Optional["SearchContextArgs"] = None
    get_context: typing.Optional["GetContextArgs"] = None
    save_context: typing.Optional["SaveContextArgs"] = None
    revise_context: typing.Optional["ReviseContextArgs"] = None
    note_trace_findings: typing.Optional["NoteTraceFindingsArgs"] = None
    prune_trace_reads: typing.Optional["PruneTraceReadsArgs"] = None
    final_result: typing.Optional["FinalResultArgs"] = None

class FinalResultArgs(BaseModel):
    completion_summary: typing.Optional[str] = None

class GetContextArgs(BaseModel):
    record_ids: typing.List[str] = Field(description='Record IDs returned by search_context or list_context. Fetch before any revision.')
    include_versions: typing.Optional[bool] = Field(default=None, description='Whether to include prior versions.')
    detail: typing.Optional[typing.Union[typing_extensions.Literal['concise'], typing_extensions.Literal['detailed']]] = Field(default=None, description='Use concise unless full version history is needed.')

class NoteTraceFindingsArgs(BaseModel):
    theme: typing.Optional[str] = Field(default=None, description='Short theme label for this finding. Leave empty only for the no-findings checkpoint.')
    line: typing.Optional[int] = Field(default=None, description='1-based trace line with supporting evidence. Leave empty only for the no-findings checkpoint.')
    quote: typing.Optional[str] = Field(default=None, description='Short evidence quote from the trace. Leave empty only for the no-findings checkpoint.')
    level: typing.Optional[types.FindingLevel] = Field(default=None, description='Durable levels only for reusable context; implementation for trace-local evidence.')

class PruneTraceReadsArgs(BaseModel):
    start_lines: typing.List[int] = Field(description='1-based start_line values from earlier read_trace calls, such as 1, 101, or 201. Never use context token counts.')

class ReadTraceArgs(BaseModel):
    start_line: typing.Optional[int] = None
    line_count: typing.Optional[int] = None

class ReviseContextArgs(BaseModel):
    record_id: typing.Optional[str] = None
    reason: typing.Optional[str] = Field(default=None, description='Short reason for the revision.')
    kind: typing.Optional[types.RecordKind] = Field(default=None, description='Must match the fetched record kind; revise_context cannot change kind.')
    title: typing.Optional[str] = Field(default=None, description='Complete improved title.')
    body: typing.Optional[str] = Field(default=None, description='Complete improved body.')
    status: typing.Optional[types.RecordStatus] = Field(default=None, description='Lifecycle status to keep or set.')
    valid_from: typing.Optional[str] = None
    valid_until: typing.Optional[str] = None
    decision: typing.Optional[str] = None
    why: typing.Optional[str] = None
    alternatives: typing.Optional[str] = None
    consequences: typing.Optional[str] = None
    user_intent: typing.Optional[str] = None
    what_happened: typing.Optional[str] = None
    outcomes: typing.Optional[str] = None

class SaveContextArgs(BaseModel):
    kind: typing.Optional[types.RecordKind] = Field(default=None, description='Use episode for the mandatory session summary; use durable kinds only for reusable project context.')
    title: typing.Optional[str] = Field(default=None, description='Short standalone title for the lasting point or episode.')
    body: typing.Optional[str] = Field(default=None, description='Compact standalone body. Do not include trace-local command logs or copied errors.')
    status: typing.Optional[types.RecordStatus] = Field(default=None, description='Use archived for routine episodes with no durable signal; active for reusable durable records.')
    valid_from: typing.Optional[str] = Field(default=None, description='Optional validity start timestamp.')
    valid_until: typing.Optional[str] = Field(default=None, description='Optional validity end timestamp.')
    decision: typing.Optional[str] = Field(default=None, description='Required only for kind=decision; omit for facts, preferences, constraints, references, and episodes.')
    why: typing.Optional[str] = Field(default=None, description='Required only for kind=decision when rationale exists; omit when the trace says no durable rationale was supplied.')
    alternatives: typing.Optional[str] = Field(default=None, description='Optional decision alternatives. Omit for non-decisions.')
    consequences: typing.Optional[str] = Field(default=None, description='Optional direct application guidance for the same durable point.')
    user_intent: typing.Optional[str] = Field(default=None, description='Required when kind=episode. Concise statement of what the user wanted in this source session.')
    what_happened: typing.Optional[str] = Field(default=None, description='Required when kind=episode. Concise statement of what the session actually did.')
    outcomes: typing.Optional[str] = Field(default=None, description='Optional concise episode outcome.')

class SearchContextArgs(BaseModel):
    query: typing.Optional[str] = Field(default=None, description='Natural-language query for the durable meaning, not \'*\' or an empty browse request.')
    kind: typing.Optional[types.RecordKind] = Field(default=None, description='Optional filter. Use only when the desired record kind is known.')
    status: typing.Optional[types.RecordStatus] = Field(default=None, description='Optional lifecycle filter.')
    valid_at: typing.Optional[str] = Field(default=None, description='Optional timestamp for historical lookup.')
    include_archived: typing.Optional[bool] = Field(default=None, description='Whether archived records should be included.')
    limit: typing.Optional[int] = Field(default=None, description='Maximum hits to return.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
