# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ExtractAgentStep": types.ExtractAgentStep,
    "stream_types.ExtractAgentStep": stream_types.ExtractAgentStep,

    "types.FinalResultArgs": types.FinalResultArgs,
    "stream_types.FinalResultArgs": stream_types.FinalResultArgs,

    "types.GetContextArgs": types.GetContextArgs,
    "stream_types.GetContextArgs": stream_types.GetContextArgs,

    "types.NoteTraceFindingsArgs": types.NoteTraceFindingsArgs,
    "stream_types.NoteTraceFindingsArgs": stream_types.NoteTraceFindingsArgs,

    "types.PruneTraceReadsArgs": types.PruneTraceReadsArgs,
    "stream_types.PruneTraceReadsArgs": stream_types.PruneTraceReadsArgs,

    "types.ReadTraceArgs": types.ReadTraceArgs,
    "stream_types.ReadTraceArgs": stream_types.ReadTraceArgs,

    "types.ReviseContextArgs": types.ReviseContextArgs,
    "stream_types.ReviseContextArgs": stream_types.ReviseContextArgs,

    "types.SaveContextArgs": types.SaveContextArgs,
    "stream_types.SaveContextArgs": stream_types.SaveContextArgs,

    "types.SearchContextArgs": types.SearchContextArgs,
    "stream_types.SearchContextArgs": stream_types.SearchContextArgs,


    "types.ExtractAction": types.ExtractAction,

    "types.FindingLevel": types.FindingLevel,

    "types.RecordKind": types.RecordKind,

    "types.RecordStatus": types.RecordStatus,

}